
spring:
  config:
    name: config-server
  profiles:
    include: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config-repo"
  application:
    name: TRANSPORTIFY_CONFIG_SERVER

server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
