spring:
  application:
    name: auth-service
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 9092
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    routes:
      enabled: true
