spring:
  application:
    name: transportify-service
  cloud:
    config:
      uri: http://localhost:8888
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    username: andreev.darko@gmail.com
    password: volimsexzadzabe
